name: Website Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests smtplib beautifulsoup4

      - name: Run monitor script
        run: python monitor.py

      - name: Check for changes and commit
        run: |
          if [ "$(ls -A saved_changes/*.html 2>/dev/null)" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add saved_changes/*.html
            git commit -m "New webpage change detected"
            git push
          else
            echo "No changes detected, skipping commit."
