name: Website Monitor

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version

      # Step 3: Create saved_changes directory if not exists
      - name: Create saved_changes directory if not exists
        run: mkdir -p saved_changes

      # Step 4: Run monitor script
      - name: Run monitor script
        run: python monitor.py

      # Step 5: Check for changes and commit
      - name: Check for changes and commit
        run: |
          if [ "$(ls -A saved_changes/*.html 2>/dev/null)" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add saved_changes/*.html
            git commit -m "New webpage change detected"
            git push
          else
            echo "No changes detected, skipping commit."
