name: Monitor Webpage for Changes

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install dependencies
        run: pip install requests

      - name: Run monitoring script
        env:
          SMTP_USER: "youssefguerboub98@gmail.com"
          SMTP_PASSWORD: "vunm mfak ymcd igcd"  # Replace with your real app password
        run: python monitor.py
